# Generated by Django 4.2.7 on 2024-01-18 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('address_name', models.CharField(max_length=100)),
                ('additional_phone_number', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('Nairobi', (('Nairobi Central', 'Nairobi Central'), ('Nairobi CBD', 'Nairobi CBD'))), ('Nakuru', (('Nakuru Central', 'Nakuru Central'), ('Nakuru CBD', 'Nakuru CBD')))], default='Nairobi', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_station', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pickup Station',
                'verbose_name_plural': 'Pickup Stations',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposited_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_type', models.CharField(max_length=20)),
                ('description', models.CharField(default='product/service purchased', max_length=100)),
                ('type', models.CharField(default='CUSTOMER', max_length=9)),
                ('payment_done', models.BooleanField(default=False)),
                ('transaction_datetime', models.DateTimeField(auto_now_add=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_datetime'],
            },
        ),
        migrations.CreateModel(
            name='UserProfuile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, upload_to='media/product_images')),
                ('currently_learning', models.TextField(blank=True)),
                ('skills_language', models.TextField(blank=True)),
                ('currently_hacking_on', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('work', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_st', models.DateTimeField(auto_now=True)),
                ('otp', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=20)),
                ('description', models.CharField(default='product/service purchased', max_length=100)),
                ('type', models.CharField(default='CUSTOMER', max_length=9)),
                ('reference', models.CharField(max_length=6)),
                ('transaction_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deposited_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transaction_datetime', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='account.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(default='', max_length=100, verbose_name='Address Name')),
                ('region', models.CharField(choices=[('Nairobi', (('Nairobi Central', 'Nairobi Central'), ('Nairobi CBD', 'Nairobi CBD'))), ('Nakuru', (('Nakuru Central', 'Nakuru Central'), ('Nakuru CBD', 'Nakuru CBD')))], default='Nairobi', max_length=200)),
                ('phone_number', models.CharField(default='', max_length=20, verbose_name='Phone Number')),
                ('additional_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Additional Phone Number')),
                ('delivery_instructions', models.CharField(blank=True, max_length=100, null=True, verbose_name='Delivery Instructions |Additional Information')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_address', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
