# Generated by Django 5.0.6 on 2024-05-29 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': '1. Payment'},
        ),
    ]
