# Generated by Django 5.0.6 on 2024-05-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_main', '0002_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': '2. Contacts'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '1. Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
