# Generated by Django 5.0.6 on 2024-05-29 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nova_main', '0003_alter_contact_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='model',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='Title',
        ),
    ]
