# Generated by Django 5.0.6 on 2024-05-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_main', '0004_rename_model_product_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title'], 'verbose_name_plural': '1. Products'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default=1, upload_to='media/product_images/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'], name='nova_main_p_id_ffb984_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='nova_main_p_title_2f521f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created'], name='nova_main_p_created_272e61_idx'),
        ),
    ]
