# Generated by Django 5.0.6 on 2024-05-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova_main', '0009_gstarted_alter_newsletter_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gstarted',
            options={'verbose_name': 'gstarted', 'verbose_name_plural': '3. gstarted'},
        ),
        migrations.AddField(
            model_name='gstarted',
            name='service_type',
            field=models.CharField(choices=[('Type Of Service', 'Type Of Service'), ('Pest Control-2', 'Home Cleaning'), ('Pest Control-3', 'Carpet Cleaning')], default='Type Of Service', max_length=20),
        ),
    ]
